### ISSUE TITLE
Trusted Types - bad name?

### ISSUE THREAD

**Issue by zcorpan** [w3c/webappsec-trusted-types#225]
I think "trusted types" is confusing and/or wrong.

These are not types (in JS). They are objects.

They're not trusted (from a web developer's perspective, anyway). I think the point is that they're *not* trusted. But they are safe (because they are sanitized).

"XSS-safe objects"?

**Comment by boazsender** [comment]
+1, I agree that "trusted" and "types" frame this interface in implementer terms is confusing from a web developer perspective. I think "safe objects" is more accessible.

**Comment by koto** [comment]
* Trusted vs safe: This distinction, and a choice for the naming is intentional. TT *are* trusted, and *are not* neccessarily safe. For example, nothing in the spec makes them sanitized, it's the web applications' choice to do so. The exact resoning for the name choice is at https://w3c.github.io/webappsec-trusted-types/dist/spec/#trusted-types. 

* Types vs objects: The intention is to explain that the security properties are moved to be expressible in JS type system. It's the types that are the focus of the spec, not individual objects that have them.

**Comment by rwaldron** [comment]
@koto This response was very helpful, thank you for taking the time to provide your insight.

**Comment by zcorpan** [comment]
Yep, thank you.

> Types vs objects: The intention is to explain that the security properties are moved to be expressible in JS type system.

Can you elaborate on this? Will the API change?

**Comment by koto** [comment]
The API already is shaped like that. For example, `HTMLDocument.write`
accepts a TrustedHTML object, so (in a TT-compliant codebase) a call of
HTMLDocument.write(string) is an error, that static analysis can pick up.
As an example, it's easy to write linter rules around TT:
https://youtu.be/1KQngEZ8qH4?t=1332

**Comment by zcorpan** [comment]
Thanks!

**Comment by boazsender** [comment]
@koto, this explanation makes sense to me. Thanks for taking the time to spell that out!
