### ISSUE TITLE
Navigating to plugins

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-trusted-types#234]
Some parts of `<embed>` and `<object>` are handled, but what if they are navigated?

**Comment by koto** [comment]
Do you mean, say, a navigation from JS to a PDF file? [ script extample would help to make sure we're talking about the same thing ] 

TT operate on a single document (wich CSP propagation rules extensing this to some other documents like `about:blank`), so that would not cover it. Similarly, you can navigate to an HTML file that, when served without TT headers, could use the DOM APIs unconstrained.
IIUC CSP `object-src`, or Fetch Metadata might prevent that navigation from succeeding, or the plugin from working.

**Comment by annevk** [comment]
I was thinking something like `<embed src=document name=x><a href=plugin target=x>hi</a>`.

**Comment by koto** [comment]
Oh, I see. Is it different to `location.href=pluginUrl` or clicking '<a href=plugin>', security wise? Now we don't restrict navigation (unless pseudo-navigation with `javascript:` URIs), the reasoning being that it likely requires a different approach, as navigation can happen outside JS.

**Comment by annevk** [comment]
Probably not, it just seems a bit weird to have endpoints for some of `embed`/`object`, but not all. Maybe that can go away if plugins go away (or all all handled as navigations, similar to `iframe`).

**Comment by koto** [comment]
Agreed; it's weird, it's a leftover from when we also had `TrustedURLs` for images and such. 

Fundamentally, we want to guard objects/embeds because they can get same-origin access to you (via scripting, or not). But this is technically a cross-document issue, which we have not yet solved, hence the inconsistency. Op top of this we have the duality of those elements that can host documents, or other content :/

**Comment by Sora2455** [comment]
Just a quick reminder that PDF files can host JavaScript and even Flash files embedded in themselves.

The only secure way of dealing with plugins is to ban them with CSP's `object-src: none`.

**Comment by koto** [comment]
At a low level (to address navigation to objects that doesn't come from setting their own attribute) , we could do what we do for scripts i.e. store the URL set via attr in a slot, hook into navigation and run some default policy function if the URL doesn't come from the slot. That would suggest we need a new type like `TrustedPluginURL`.

IIUC plugins are not going away anytime soon? /cc @mikewest

**Comment by mikewest** [comment]
> IIUC plugins are not going away anytime soon?

Flash dies at the end of 2020 for really reals, but Chromium at least will still depend on PPAPI today for things like PDFium. The goal AFAIK is to deprecate PPAPI as well, but I don't know of a solid schedule.

**Comment by koto** [comment]
Since we've added `require-trusted-types-for 'script'`, it seems like guarding object / embeds should be guarded by a new keyword - `'object'`.

**Comment by annevk** [comment]
I think ideally `embed`/`object`/`frame`/`iframe` all have the same guards. If folks use the plugin system to guard something else we might end up stuck with it which would be unfortunate as we would not be able to simplify those elements further.

**Comment by koto** [comment]
Could you clarify? I didn't understand the advantage of controlling both together via a single setting. 

Using iframes is not particularly worrying if you trust Same Origin Policy, while use of plugins in one's application carries different risks. In TT terms, this suggests we need two separate types like `TrustedFrameURL` and `TrustedPluginSrc` and I wouldn't want to make it one *type*. We could control eforcement for both or them together under `require-trusted-types 'frames-and-plugins'`, but I don't see how that enables future simplification, especially since CSP has directives for frames / objects separately.

**Comment by annevk** [comment]
The thing is that what's now a plugin might be an image or document in the future. And there's no way to distinguish them.

Perhaps the real primitive is that someone is trying to execute a plugin for the document and being able to disable that without a real obvious API entry point as there is none.

**Comment by koto** [comment]
Agreed, to guard plugins comprehensively, we need better primitives than TT - if this primitive can be reused for iframes, that's fine. I added a [security consideration section](https://w3c.github.io/webappsec-trusted-types/dist/spec/#plugins) to make that clear for the authors. Thanks!
