### ISSUE TITLE
Access the source/file that is using the 'default' policy

### ISSUE THREAD

**Issue by jeberly** [w3c/webappsec-trusted-types#295]
Is there a way to know what file/source/line is using a default createHTML policy? 

Our use case is we have a default policy mainly so we can use trusted types with Svelte. It would be nice to output console warnings if our own future code is using the default policy, instead of a custom policy so we are alerted to that and can write a custom policy for it, or rewrite the code to avoid the need of a trusted type altogether. 

Best I can tell createHTML only has access to `string` and `sink` right now.

Something like this...

```
export const initDefaultTrustedTypePolicy = () => {
  window.trustedTypes.createPolicy('default', {
    createHTML: (string) =>
      if (notVendorCode) console.warn("ourcode.js line 23 is using the default policy, refactor")
      DOMPurify.sanitize(string, { RETURN_TRUSTED_TYPE: true }),
  });
};
```

**Comment by Sora2455** [comment]
I haven't tried this myself, but you could try the [stacktrace property on error objects](https://stackoverflow.com/a/635852/7077589):
`function stackTrace() {
    var err = new Error();
    return err.stack;
}`

**Comment by koto** [comment]
In production, the error stack like @Sora2455 shows is probably the most practical way. The API itself doesn't provide the access to the callsite of the default policy, sadly. Introspection in JS programs is, in general, discouraged, which makes it difficult for us to expose this data to the default policy :(

What might also work in test environment is if you set up Report-Only mode and return `null` from the default policy whenever you detect (from the Error stack) the location to be not the expected one. That way, the [SecurityPolicyViolationEvent](https://developer.mozilla.org/en-US/docs/Web/API/SecurityPolicyViolationEvent) (which you can listen to) should have the file, line and column of the offending code.

I'll close this ticket, as we don't currently plan to expose more data to the default policy, but am happy to continue discussing what the workaround could be.

**Comment by Siegrift** [comment]
This might also help to bless addition bundler code and nothing more. 
What I mean is specifically hot reloading of the code. Bundlers like to add code like: https://github.com/snowpackjs/snowpack/blob/fc6c1417a09ac85e02730033660391d299a5fd97/snowpack/assets/hmr-error-overlay.js#L891 to simplify the dev experience. Unfortunately this breaks with TT enforcement.

The ideal solution is to fix it in the bundlers, unfortunately bundlers might be conservative about adding TT code and might not want to accept such patches. I am not sure if there is generic way how to solve this though - In my case I just check whether the unsafe value contains some substring (which is definitely not ideal).

@koto was there any way how to approach this problem in better way?

**Comment by koto** [comment]
@otherdaniel is there actually a way for Blink to know which callsite generated the violation? We have this data for the violation, is there a way to expose it to the default policy?

**Comment by Siegrift** [comment]
@otherdaniel @koto Any update regarding this? I feel this is very important for the developers who want to migrate to TT.

Key points:
- It's very difficult (or impossible) to fix the violations in third party code
- TT integrations in popular tools (e.g. bundlers, UI frameworks...) is hard and it is a long process
- It's inevitable to use default policy to cherry pick "allowed/trusted" sinks

However, as currently implemented, the information provided in the default policy brings very little context. It is impossible to differentiate to which sink the value is being assigned. Common examples developer would want to do:
- Allow all sinks coming from a file - e.g. allow all sinks in webpack (or any other bundler) code
- Have a stack trace. This should contain the information about sink, the filename and previous function calls.

For example, if you want to add TT to your nextJS app, you need the following default policy in order to at least start the app in dev mode https://github.com/Siegrift/biti-project/blob/main/ant-nextjs/public/register-default-policy-for-dev.js.

I don't know how hard it is to provide more information, but I think this would be very valuable.
