### ISSUE TITLE
Clarify in spec - JS 'this' in policy.createXXX()

### ISSUE THREAD

**Issue by saganatt** [w3c/webappsec-trusted-types#78]
Found and pointed at by yukishiino

In this part of JS code:
`function getHTML(s) { return this.foo + " " + s; }`
`let policy = window.trustedTypes.createPolicy('SomeName', { createHTML: s => getHTML(s) })`

What would we like `this`to point to? 2 possibilities:
1) global object, i.e. window --> `this.foo` will refer to global `var foo`
2) policy itself --> `this.foo` == `policy.foo`. This would also enable also e.g. getting policy name or other properties like this:
`function myCreateHTML(input) { console.log(this.name); }`
`let policy = window.trustedTypes.createPolicy('SomeName', { createHTML: s => myCreateHTML(s) })`
`policy.createHTML('something')`

We should have this choice of behaviour explained in specification as well.

**Comment by koto** [comment]
Actually, I would argue `this` should be `undefined`, at least that would be in sync with the approach we took so far when [wrapping the policy](https://github.com/WICG/trusted-types/blob/77f81188873a95dd35250607d6a27708ea272391/src/trustedtypes.js#L229-L258)

We're trying to discourage a pattern where the policy behavior changes at runtime - to make policy reviews easier.  For example, we'd like the following to not work:

``
function pol() {}
pol.createHTML = (s) => {console.log(this, s); return 'pol' + s}
pol.createURL = (s) => {this.createHTML = (s) => {console.warn(this, s); return 'hijacked' + s}; console.log('hijacking'); return s}
``

Currently, when wrapping the policy we actually separate & freeze each `createXYZ`. 

While I'd like to avoid `this` pointing to the inner policy, perhaps it might point to this new wrapped policy object (`TrustedTypesPolicy`)? Currently `this` points to a global object, which isn't great either, we shouldn't leak global object references. @mikesamuel , WDYT?

**Comment by mikesamuel** [comment]
Recommendations first; we should 
*  not try to pass anything via `this`,
*  recommend that policy authors `'use strict'` so that `this` is consistently `null`
*  see whether there's anything we could pass via named parameters to `getHTML` to support policy authors who want to reuse `createHTML` functions across multiple policies
*  not expose internal implementation objects either via `this` or named parameters

----

@saganatt said
> We should have this choice of behaviour explained in specification as well.

@koto said
> While I'd like to avoid this pointing to the inner policy

+1 to both

----

@koto said
> Actually, I would argue this should be undefined

If we assume strict mode, isn't `null` the default.  In non-strict mode, any non-object value is replaced with the global object.  Hence my recommendation about `"use strict"` above.

----

Apologies if everyone already knows about `this` and lambdas but I'm going to spell them out since the meaning of the code sample depends on them.

@saganatt said
> ```js
> function getHTML(s) { return this.foo + " " + s; }
> let policy = window.trustedTypes.createPolicy('SomeName', { createHTML: s => getHTML(s) })
> ```

Lambdas inherit `this` from the outer scope per [Tennant's correspondence principle](http://gafter.blogspot.com/2006/08/tennents-correspondence-principle-and.html):

> The principle dictates that an expression or statement, when wrapped in a closure and then immediately invoked, ought to have the same meaning as it did before being wrapped in a closure.

You can see this via:

```js
const notWindow = { toString() { return 'not window' } };
Reflect.apply(() => this, notWindow, []) === window; // true
// vs
Reflect.apply(function () { return this }, notWindow, []) === notWindow; // true

// `this` inherited from innermost non-lambda context per Tennent's
const obj = {
  toString() { return 'obj' },
  f() {
    return (() => this)() === obj;
  }
};
obj.f();  // true
```

so regardless of what `window.trustedTypes` does `s => ...` does not have access to the `this` from `window.trustedTypes`.

-----

I'm going to address the example without the lambda:

```js
function getHTML(s) { return this.foo + " " + s; }
let policy = window.trustedTypes.createPolicy(
    'SomeName', { createHTML: getHTML })
```

Using `this` might make it easier to share a single `createHTML` function among multiple policies but whatever we pass via `this` we could pass via named parameters.

Pros of named parameters relative to `this`
* they have  a name that the author can use to set expectations
* they forward consistently via `...rest` and through lambdas
* they can be passed via normal function calls instead of creating an array to use with `Reflect.apply`, or trusting `fn.call` to do the right thing.

Cons of named parameters relative to `this`
* Have a clear meaning in a function body directly nested in a `class` declaration.

The meaning of `this` per the last rule would be the bag of properties passed to `createPolicy`.

But that bag of properties is a transient object that does not provide a trustworthy path to any policy-related operations.  If `window.trustedtypes` does not rely on it not to be mutated after `createPolicy` ends, policy authors would be wise not to either.

**Comment by koto** [comment]
To document the behaviour of the Chrome implementation, `this` in a policy now returns a global object.

```
data:text/html,<meta http-equiv="Content-Security-Policy" content="trusted-types *"><script>TrustedTypes.createPolicy('default', { createHTML:(s) => {console.log(this); debugger; return s} }, true); document.write('')</script>
```
